### PR TITLE
Update 4-drucker-auf-clients-einrichten.rst

### PR DESCRIPTION
**Pull request by michaelkohls**
Some minor corrections: 
menu name for uploading drivers and command name for assigning driver to printer

### CODE REVIEW

**Comment by MachtDochNix** [comment]
Wow, that was fast. Congratulations on your first patch.
Can the issue be closed with this? If so, let me know or just do it yourself.

**Comment by michaelkohls** [comment]
What is the corresponding issue? How can i close it?

**Comment by MachtDochNix** [comment]
A picture says more than a kilo of words. (hashtag+number) shows you the issue.

grafik

Issue Close request should be found below.

**Comment by michaelkohls** [comment]
Okay. Thank you for your help.

**Pull request merged**
