### PR TITLE
v7 - pull all TOC together

### LINKED ISSUE #135: caption in toctree untranslateable
Using captions in toctrees looks nice, but their are some problems:
* their are not translated (maybe thats fixed in a more recent version of sphinx)
* https://github.com/sphinx-doc/sphinx/issues/3169

So I suggest to put all the Table of content in one main toctree.

### PR DESCRIPTION
**Pull request by jolly-jump**
fix #135

### CODE REVIEW

**Comment by jollyzsher** [comment]
@zefanja 
what do you think of this?

**Comment by zefanja** [comment]
I haven't had the time to check the latest version of sphinx an see if they support translating of toc tree captions. It would be nice, because they look much better :) Otherwise we can merge this.

**Comment by jollyzsher** [comment]
Hi,

i just added the TOCs again: they just look so much nicer.
As a compromise - if the new sphinx can not translate the captions - I just used the english terms to begin with - so no need to translate. German users will understand.

**Comment by clefebvre** [comment]
Hi @jolly-jump, @zefanja, I hope this will help you. We went through the very same issue.

Basically sphinx-build didn't pick up toctree captions with our version of sphinx when building the PO files.

This isn't a solution per-se, but a workaround. We just added the section names into a sections.rst document. That document isn't used at all within our guide, but it's picked up by make-gettext and so we get a sections.po generated.

We're also merging all the po into one (for other reasons.. we use Launchpad to do the translations and it's just easier that way), so it just works then... index.po and all the po end up having every single msgid/msgstr from all the different rst pages, and we end up with translated sections on read the docs.

https://github.com/linuxmint/doc-installation-guide
http://linuxmint-installation-guide.readthedocs.io/fr/latest/
https://github.com/linuxmint/doc-installation-guide/commit/6092b49ed91e23906df6ed8f74d0c51203c88b4d
https://github.com/linuxmint/doc-installation-guide/commit/a1bf53caf798fb4f6ce6ac143a3e85670b621b7e

hope it helps, good luck ;)

**Comment by zefanja** [comment]
Hi @clefebvre ,

thanks for your helpful comment! This may be a workaround for our problem, too. I just found this: http://www.sphinx-doc.org/en/stable/config.html#confval-gettext_additional_targets I need to test this, but may it does the trick.

**Comment by clefebvre** [comment]
Cool, that looks like a good lead.

**Pull request closed without merging**
