### PR TITLE
Structure of the LINBO client description adapted/changed

### PR DESCRIPTION
**Pull request by MachtDochNix**

### CODE REVIEW

**Comment by MachtDochNix** [comment]
@cweikl: Can you check why my PR did not result in the online update of v7.1.

**Comment by cweikl** [comment]
Having update the local v7.1 repository I run make clean && make html. The output indicates that there are still some errors concerning toctree references.
Take a look:

`/home/wk/linuxmuster-docs/main/source/index.rst:88: WARNING: toctree contains reference to nonexisting document 'clients/client_templates/index'
/home/wk/linuxmuster-docs/main/source/index.rst:108: WARNING: toctree contains reference to nonexisting document 'migration/linux-client-migration'
/home/wk/linuxmuster-docs/main/source/index.rst:117: WARNING: toctree contains reference to nonexisting document 'clients/index'
/home/wk/linuxmuster-docs/main/source/index.rst:117: WARNING: toctree contains reference to nonexisting document 'clients/client_templates/index'
`
The creation failed (read the docs) indicating `Fehler

We encountered a problem with a command while building your project. To resolve this error, double check your project configuration and installed dependencies are correct and have not changed recently.`.
If you look at the output the above arrors are referenced. Therefore, I assume that the above mentioned errors are the reason for read the docs to fail.
Bye
Chris

**Comment by MachtDochNix** [comment]
OK! I will check, again. 
grafik

I will have a look at the reported files!?
Thanks and bye
Thorsten

**Comment by MachtDochNix** [comment]
Before:

`
118 .. toctree::
119   :maxdepth: 4
120   :caption: Clientverwaltung
121   :hidden:
122 
123   clients/index
124   clients/client_templates/index
125   clients/use_linbo4/index
126   clients/postsync/index
127   clients/leoclient2/index
128    ..  clients/linbo/index
129    ..  clients/windows10clients/index
130    ..  clients/linux-clients/index
`
After:

`
118 .. toctree::
119   :maxdepth: 4
120   :caption: Clientverwaltung
121   :hidden:
122 
123   clients/index
124   clients/client_templates/index
125   clients/use_linbo4/index
126   clients/postsync/index
127   clients/leoclient2/index
128 
129 ..  clients/linbo/index
130 ..  clients/windows10clients/index
131 ..  clients/linux-clients/index
`
Next try! PR #714

**Pull request merged**
